import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── Tokens shadcn ──────────────────────
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // ── Vos couleurs Material You ───────────
        "surface-container": "#ededf9",
        "on-secondary-container": "#626567",
        error: "#ba1a1a",
        "surface-tint": "#0053db",
        "primary-container": "#2563eb",
        "inverse-on-surface": "#f0f0fb",
        "primary-fixed": "#dbe1ff",
        "inverse-primary": "#b4c5ff",
        tertiary: "#943700",
        "on-primary-fixed-variant": "#003ea8",
        "on-primary-fixed": "#00174b",
        "tertiary-container": "#bc4800",
        "on-primary-container": "#eeefff",
        "on-surface-variant": "#434655",
        "surface-container-highest": "#e1e2ed",
        "secondary-container": "#e0e3e5",
        "surface-dim": "#d9d9e5",
        "surface-container-low": "#f3f3fe",
        "on-background": "#191b23",
        "primary-fixed-dim": "#b4c5ff",
        "outline-variant": "#c3c6d7",
        "tertiary-fixed": "#ffdbcd",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#faf8ff",
        outline: "#737686",
        "on-secondary-fixed": "#191c1e",
        "surface-variant": "#e1e2ed",
        "tertiary-fixed-dim": "#ffb596",
        "on-surface": "#191b23",
        "inverse-surface": "#2e3039",
        surface: "#faf8ff",
        "on-tertiary-fixed": "#360f00",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffede6",
        "secondary-fixed": "#e0e3e5",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#c4c7c9",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#7d2d00",
        "surface-container-high": "#e7e7f3",
        "on-secondary-fixed-variant": "#444749",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "var(--radius)",
        xl: "calc(var(--radius) + 0.25rem)",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        xl: "32px",
        lg: "24px",
        md: "16px",
        sm: "8px",
        xs: "4px",
        "2xl": "48px",
        "3xl": "64px",
        gutter: "24px",
        base: "4px",
      },
      fontFamily: {
        sans: ["Geist", "sans-serif"],
        display: ["Geist"],
        body: ["Geist"],
        label: ["Geist"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        h1: ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        h2: ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        h3: ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5" }],
        "body-sm": ["14px", { lineHeight: "1.5" }],
        "body-lg": ["18px", { lineHeight: "1.6" }],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}

export default config